language: ruby
cache: bundler
rvm:
  - 2.0.0-p598
  - 2.1.4
  - 2.2.0
  - rbx-2
  - jruby

gemfile:
  - gemfiles/activerecord_4.0.gemfile
  - gemfiles/activerecord_4.1.gemfile
  - gemfiles/activerecord_4.2.gemfile
  - gemfiles/activerecord_edge.gemfile

addons:
  postgresql: '9.3'

matrix:
  allow_failures:
    - gemfile: gemfiles/activerecord_edge.gemfile

before_script:
  - psql -c 'create database ltree_rails_test;' -U postgres

script: 'bundle exec rspec'
